RingoMedaTest/Models/ErrorViewModel.cs
namespace RingoMedaTest.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RingoMedaTest/Controllers/DepartmentController.cs
using Application.DTOs.Departments;
using Application.Interfaces.IService;
using Microsoft.AspNetCore.Mvc;

namespace RingoMediaTest.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDepartmentService _service;
        public DepartmentController(IDepartmentService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var departments = await _service.GetAllAsync();

            return View(departments);
        }
        public async Task<IActionResult> Details(long id)
        {
            var department = await _service.GetDepartmentHierarchyAsync(id);

            return View(department);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Departments =await GetDepartmentList();
            return View(new AddDepartmentDto());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddDepartmentDto addDepartment)
        {
            ViewBag.Departments =await GetDepartmentList();
            if (!ModelState.IsValid)
            {
                return View(addDepartment);
            }
            await _service.AddAsync(addDepartment);
            return RedirectToAction("Index");
        }
        private async Task<List<DepartmentDto>> GetDepartmentList()
        {
            return await _service.GetAllAsync();
        }
    }
}

RingoMedaTest/Controllers/ReminderController.cs
using Application.DTOs.Reminders;
using Application.Interfaces.IService;
using Application.Service;
using Microsoft.AspNetCore.Mvc;

namespace RingoMediaTest.Controllers
{
    public class ReminderController : Controller
    {
        private readonly IReminderService _reminderService;

        public ReminderController(IReminderService reminderService)
        {
            _reminderService = reminderService;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Add(ReminderDto reminder)
        {
            _reminderService.ScheduleHangFireJob(reminder);

            return RedirectToAction("Index");
        }
    }
}

RingoMedaTest/Views/Department/Create.cshtml
@model Application.DTOs.Departments.AddDepartmentDto

@{
    ViewData["Title"] = "Create";
    var departments = new SelectList(ViewBag.Departments, "Id", "Name");
}

<div class="row justify-content-center">

<div class="col-xl-10 col-lg-12 col-md-9">

    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                <div class="col-lg-6">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Add New Department</h1>
                        </div>
                            <form class="user" asp-action="Create" enctype="multipart/form-data">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input class="form-control form-control-user"
                                       id="exampleInputEmail" aria-describedby="emailHelp"
                                       asp-for="Name"
                                       placeholder="Enter Your Name...">
                                    <span asp-validation-for="Name" class="text-danger"></span>

                            </div>
                            <div class="form-group">
                                 <label asp-for="Logo" class="control-label"></label> 
                                <input type="file" asp-for="Logo" class="form-control-user">
                                    <span asp-validation-for="Logo" class="text-danger"></span>

                            </div>
                            <div class="form-group">
                                 <label class="control-label">Department</label>
                                    <select asp-items="departments" asp-for="ParentDepartmentId" class="form-control-user">
                                        <option value="null">---- Choose ----</option>
                                        </select>
                            </div>

                            <button type="submit" class="btn btn-primary btn-user btn-block">
                                Add
                            </button>
                            <hr>
                            <a asp-action="Index" class="btn btn-google btn-user btn-block">
                                <i class="fab fa-google fa-fw"></i> Back to list
                            </a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

        </div>

@* @section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
} *@

RingoMedaTest/Views/Department/Details.cshtml
@model Application.DTOs.Departments.DepartmentHierarchyDto

@{
    ViewData["Title"] = "Details";
}

<h1 class="h3 mb-0 text-gray-800">Hierarchical Tree Structure</h1>
<nav class="hierarchy">
    @foreach(var parent in Model.Parents)
    {
        @:<ul>
        @:    <li>
        @Html.ActionLink(parent.Name.ToString(), "Details", new { id = parent.Id })

    }
    <ul>
        <li>
            @Html.ActionLink(@Model.Department.Name, "Details", new { id = @Model.Department.Id })

            @if(Model.Children.Count() > 0)
            {
            <ul>
                @foreach(var child in Model.Children)
                {
                    <li>
                        @Html.ActionLink(child.Name.ToString(), "Details", new { id = child.Id })
                    </li>
                }
            </ul>
            }
        </li>
    </ul>
    @for(int i = 0; i < Model.Parents.Count; i++)
    {
        @:</li>
        @:</ul>
    }
</nav>

RingoMedaTest/Views/Department/Index.cshtml
@model IEnumerable<Application.DTOs.Departments.DepartmentDto>

@{
    ViewData["Title"] = "Index";
}

<h1 class="h3 mb-0 text-gray-800">Index</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Logo)
            </th>
@*             <th></th>
 *@        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.Id.ToString(), "Details", new { id = item.Id })

                </td>
                <td>
                    @Html.ActionLink(item.Name.ToString(), "Details", new { id = item.Id })
                </td>
                <td>
                    <img style="width:50px" src="@item.Logo" />
                    @* @Html.DisplayFor(modelItem => item.Logo) *@
                </td>
               @*  <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td> *@
            </tr>
        }
    </tbody>
</table>

RingoMedaTest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RingoMedaTest/Views/Reminder/Index.cshtml
@model Application.DTOs.Reminders.ReminderDto
@{
    ViewData["Title"] = "Index";
}

<div class="row justify-content-center">

<div class="col-xl-10 col-lg-12 col-md-9">

    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                <div class="col-lg-6">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Set Reminder</h1>
                        </div>
                            <form class="user" asp-action="Add">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input class="form-control form-control-user"
                                       id="exampleInputEmail" aria-describedby="emailHelp"
                                       asp-for="Name"
                                       placeholder="Enter Your Name...">
                                    <span asp-validation-for="Name" class="text-danger"></span>

                            </div>
                            <div class="form-group">
                                 <label asp-for="RemindTime" class="control-label"></label>
                                    <input asp-for="RemindTime" class="form-control-user">
                                    <span asp-validation-for="RemindTime" class="text-danger"></span>

                            </div>

                            <button type="submit" class="btn btn-primary btn-user btn-block">
                                Add Reminder
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

        </div>

@* @section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
} *@

RingoMedaTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Fjalla+One' rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel='stylesheet' href='https://codepen.io/joellesenne/pen/pdMPdW.css'>
    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">
    <link href="~/css/site.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Ringo Media </div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Divider -->
            <hr class="sidebar-divider">
            <li class="nav-item">
                <a class="nav-link" asp-action="Index" asp-controller="Department">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Department</span>
                </a>
            </li><li class="nav-item">
                <a class="nav-link" asp-action="Index" asp-controller="Reminder">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Reminder</span>
                </a>
            </li>

            <!-- Nav Item - Tables -->
           

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

          

        </ul>

        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                   
                   

                  

                </nav>
                <div class="container-fluid">
      @RenderBody()

  </div>

            </div>


        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>



</body>

</html>